layout_spectrum: 0.5813010403081442
typography_spectrum: 0.17738760063397044
color:
  brandStrength: 0.6771112861819935
  lightness: 0.8175257251541693
  saturation: 0.9070015768852491
  rhythmicContrast: 0.011655334871870898
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: mygallery
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7f8390-280e-4db8-99a1-6d3571a169e4.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7f8390-280e-4db8-99a1-6d3571a169e4.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: my gallery
description: a fake portfolio of work..
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0de8f25-2084-4feb-8173-56fd32238723.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c8e5952-b3e1-47f2-a620-27b94647bf9a.png
url: 'https://gallery.abc-xyz.us/'
