typography_spectrum: 0.172020254111065
color:
  brandStrength: 0.671285973687352
  lightness: 0.1381132474277021
  saturation: 0.9090199714816997
  rhythmicContrast: 0.01197968900314357
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
github: true
layout_spectrum: 0.9418318385752563
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c8e5952-b3e1-47f2-a620-27b94647bf9a.png
name: gallery
url: 'http://thegrid.ai/galleryabc'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Gallery on own page
    id: c70bccbc-8cbb-4479-9024-eb3281bd30f8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0de8f25-2084-4feb-8173-56fd32238723.png
title: the gallery
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7f8390-280e-4db8-99a1-6d3571a169e4.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7f8390-280e-4db8-99a1-6d3571a169e4.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: a fake portfolio of work..
purpose:
  - type: external
    url: 'http://thegrid.ai/abcxyz'
    label: abc.. xyz
